import React from "react"; import { motion } from "framer-motion";

function Navbar() { return ( <nav className="max-w-6xl mx-auto p-4 flex items-center justify-between"> <div className="flex items-center gap-3"> <div className="w-10 h-10 rounded-md bg-gradient-to-br from-teal-400 to-blue-500 flex items-center justify-center text-white font-semibold">PP</div> <div> <div className="font-semibold">Phuvanenthran P</div> <div className="text-xs text-slate-500">IT Graduate · Data & Cloud Enthusiast</div> </div> </div> <div className="hidden md:flex items-center gap-6 text-sm text-slate-600"> <a href="#projects" className="hover:text-slate-900">Projects</a> <a href="#skills" className="hover:text-slate-900">Skills</a> <a href="#experience" className="hover:text-slate-900">Experience</a> <a href="#certifications" className="hover:text-slate-900">Certifications</a> <a href="#contact" className="hover:text-slate-900">Contact</a> </div> </nav> ); }

function Hero() { return ( <header className="bg-gradient-to-br from-slate-900 to-teal-500 text-white py-16"> <motion.div className="max-w-5xl mx-auto px-6 grid md:grid-cols-2 gap-8 items-center" initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }} > <div> <h1 className="text-4xl md:text-5xl font-bold leading-tight">Phuvanenthran P</h1> <p className="mt-4 text-lg md:text-xl max-w-xl">IT Graduate • Python & Data Analytics • AWS Cloud Practitioner</p> <p className="mt-4 text-sm opacity-90 max-w-lg"> I build clear, maintainable data solutions and cloud-ready tools. I focus on practical results — clean data pipelines, insightful dashboards, and automation that saves time. </p> <div className="mt-6 flex gap-3"> <a href="#projects" className="bg-white text-slate-900 px-4 py-2 rounded shadow">View Projects</a> <a href="mailto:phuvan0205@gmail.com" className="border border-white px-4 py-2 rounded">Contact Me</a> </div> </div> </motion.div> </header> ); }

function Skills() { const skills = [ { name: "Python (Pandas, NumPy, Matplotlib)", percent: 85, color: "bg-teal-500" }, { name: "SQL / MySQL", percent: 80, color: "bg-indigo-500" }, { name: "AWS", percent: 75, color: "bg-amber-500" }, { name: "Linux / Server", percent: 80, color: "bg-emerald-500" } ]; return ( <motion.section id="skills" className="bg-white p-6 rounded-lg shadow max-w-6xl mx-auto my-12" initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} viewport={{ once: true }} > <h2 className="text-xl font-semibold mb-4">Skills</h2> <div className="grid md:grid-cols-2 gap-4"> {skills.map((skill, idx) => ( <div key={idx}> <div className="text-sm">{skill.name}</div> <div className="w-full bg-slate-100 rounded h-3 mt-2 overflow-hidden"> <motion.div className={${skill.color} h-3} initial={{ width: 0 }} whileInView={{ width: ${skill.percent}% }} transition={{ duration: 1, delay: idx * 0.2 }} viewport={{ once: true }} ></motion.div> </div> </div> ))} </div> </motion.section> ); }

function Projects() { const projects = [ { title: "Stock Market Trend Reporting", description: "Structured reports and visualizations to assist basic investment tracking.", icon: "📈", link: "https://github.com/Phuvanenthran-P/Projects/blob/main/Real_Time_Stock_Market_Dashboard.ipynb" }, { title: "Phone Usage Behavior Analysis (India)", description: "Data cleaning, trend analysis and region-wise visualizations for mobile usage patterns.", icon: "📱", link: "https://github.com/Phuvanenthran-P/Projects/blob/main/Phone_Usage_Analysis.ipynb" } ]; return ( <motion.section id="projects" className="max-w-6xl mx-auto p-6" initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} viewport={{ once: true }} > <h2 className="text-xl font-semibold mb-4">Projects</h2> <div className="grid md:grid-cols-2 gap-6"> {projects.map((p, idx) => ( <motion.div key={idx} className="bg-white p-4 rounded-lg border shadow-sm" whileHover={{ scale: 1.03 }} > <div className="flex items-start gap-4"> <div className="w-12 h-12 rounded bg-slate-100 flex items-center justify-center">{p.icon}</div> <div> <h3 className="font-semibold">{p.title}</h3> <p className="text-sm text-slate-600 mt-1">{p.description}</p> <div className="mt-3"> <a href={p.link} target="_blank" rel="noopener noreferrer" className="text-sm underline">View Project</a> </div> </div> </div> </motion.div> ))} </div> </motion.section> ); }

function Experience() { return ( <motion.section id="experience" className="bg-white p-6 rounded-lg shadow max-w-6xl mx-auto my-12" initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} viewport={{ once: true }} > <h2 className="text-xl font-semibold mb-4">Experience</h2> <div className="flex items-start gap-4"> <div className="text-sm text-slate-500">Nov 2024 – Dec 2024</div> <div> <div className="font-medium">Data Analyst Associate Intern, Excelerate</div> <ul className="list-disc ml-5 text-sm text-slate-600 mt-2"> <li>Monitored and reported social media campaign performance.</li> <li>Prepared daily engagement and performance trend reports.</li> <li>Assisted in formatting and delivering insights to improve outreach.</li> </ul> </div> </div> </motion.section> ); }

function Certifications() { const certs = [ { name: "AWS Cloud Practitioner", link: "https://www.credly.com/badges/5f13be1b-44f7-4f71-8d86-0a1cb5d0ff67" }, { name: "Data Science with Python — Qtree", link: "#" }, { name: "AWS re/Start Program", link: "#" } ]; return ( <motion.section id="certifications" className="bg-white p-6 rounded-lg shadow max-w-6xl mx-auto my-12" initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} viewport={{ once: true }} > <h2 className="text-xl font-semibold mb-4">Certifications</h2> <div className="flex gap-4 flex-wrap"> {certs.map((c, idx) => ( <a key={idx} href={c.link} target="_blank" rel="noopener noreferrer" className="px-4 py-2 border rounded text-sm hover:bg-slate-100">{c.name}</a> ))} </div> </motion.section> ); }

function Contact() { return ( <motion.section id="contact" className="bg-white p-6 rounded-lg shadow max-w-6xl mx-auto my-12" initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} viewport={{ once: true }} > <h2 className="text-xl font-semibold mb-4">Contact</h2> <p className="text-sm text-slate-600 mb-4">Available for internship and entry-level roles in data, cloud, and automation. Reach out via email or LinkedIn.</p> <div className="text-sm space-y-2"> <div><strong>Email:</strong> <a href="mailto:phuvan0205@gmail.com" className="underline">phuvan0205@gmail.com</a></div> <div><strong>Phone:</strong> <a href="tel:+919566472504" className="underline">+91 9566472504</a></div> <div className="flex gap-3 mt-3"> <a href="https://github.com/Phuvanenthran-P/Projects" target="_blank" className="px-3 py-2 border rounded text-sm">GitHub</a> <a href="https://www.linkedin.com/in/phuvanenthran-p-316a53287/" target="_blank" className="px-3 py-2 border rounded text-sm">LinkedIn</a> </div> </div> </motion.section> ); }

export default function Portfolio() { return ( <div> <Navbar /> <Hero /> <Skills /> <Projects /> <Experience /> <Certifications /> <Contact /> <footer className="text-center text-sm text-slate-500 py-6">© {new Date().getFullYear()} Phuvanenthran P — Built with clarity and practicality.</footer> </div> ); }

